/*####COPYRIGHTBEGIN####
 -------------------------------------------
 Copyright (C) 2012 Steve Karg

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to:
 The Free Software Foundation, Inc.
 59 Temple Place - Suite 330
 Boston, MA  02111-1307, USA.

 As a special exception, if other files instantiate templates or
 use macros or inline functions from this file, or you compile
 this file and link it with other works to produce a work based
 on this file, this file does not by itself cause the resulting
 work to be covered by the GNU General Public License. However
 the source code for this file must still be made available in
 accordance with section (3) of the GNU General Public License.

 This exception does not invalidate any other reasons why a work
 based on this file might be covered by the GNU General Public
 License.
*
*****************************************************************************************
*
*   Modifications Copyright (C) 2017 BACnet Interoperability Testing Services, Inc.
*
*   July 1, 2017    BITS    Modifications to this file have been made in compliance
*                           with original licensing.
*
*   This file contains changes made by BACnet Interoperability Testing
*   Services, Inc. These changes are subject to the permissions,
*   warranty terms and limitations above.
*   For more information: info@bac-test.com
*   For access to source code:  info@bac-test.com
*          or      www.github.com/bacnettesting/bacnet-stack
*
****************************************************************************************/

#include <stdint.h>
#include "bacenum.h"
#include "bacdef.h"
#include "bacdcode.h"
#include "bacenum.h"
#include "rpm.h"
#include "rp.h"
#include "proplist.h"

#ifndef BACNET_PROPERTY_LISTS
#define BACNET_PROPERTY_LISTS 0
#endif

#if ( BACNET_PROPERTY_LISTS == 1 )

/** @file proplist.c  List of Required and Optional object properties */
/* note: the PROP_PROPERTY_LIST is NOT included in these lists, on purpose */

        // compare these lists against BTC BACnetObjects.cs
        // Here is a clue: BC       E:\Dev\BITS\BACnet Dev\BACnetLibrary\BACnetObjects.cs
        //                          E:\Dev\BITS Reference Stack\BITS Reference Stack - Feature Creep\src\proplist.c

static const BACNET_PROPERTY_ID Default_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Device_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_SYSTEM_STATUS,
    PROP_VENDOR_NAME,
    PROP_VENDOR_IDENTIFIER,
    PROP_MODEL_NAME,
    PROP_FIRMWARE_REVISION,
    PROP_APPLICATION_SOFTWARE_VERSION,
    PROP_PROTOCOL_VERSION,
    PROP_PROTOCOL_REVISION,
    PROP_PROTOCOL_SERVICES_SUPPORTED,
    PROP_PROTOCOL_OBJECT_TYPES_SUPPORTED,
    PROP_OBJECT_LIST,
    PROP_MAX_APDU_LENGTH_ACCEPTED,
    PROP_SEGMENTATION_SUPPORTED,
    PROP_APDU_TIMEOUT,
    PROP_NUMBER_OF_APDU_RETRIES,
    PROP_DEVICE_ADDRESS_BINDING,
    PROP_DATABASE_REVISION,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Device_Properties_Optional[] = {
    PROP_LOCATION,
    PROP_DESCRIPTION,
    PROP_STRUCTURED_OBJECT_LIST,
    PROP_MAX_SEGMENTS_ACCEPTED,
    PROP_VT_CLASSES_SUPPORTED,
    PROP_ACTIVE_VT_SESSIONS,
    PROP_LOCAL_TIME,
    PROP_LOCAL_DATE,
    PROP_UTC_OFFSET,
    PROP_DAYLIGHT_SAVINGS_STATUS,
    PROP_APDU_SEGMENT_TIMEOUT,
    PROP_TIME_SYNCHRONIZATION_RECIPIENTS,
    PROP_MAX_MASTER,
    PROP_MAX_INFO_FRAMES,
    PROP_CONFIGURATION_FILES,
    PROP_LAST_RESTORE_TIME,
    PROP_BACKUP_FAILURE_TIMEOUT,
    PROP_BACKUP_PREPARATION_TIME,
    PROP_RESTORE_PREPARATION_TIME,
    PROP_RESTORE_COMPLETION_TIME,
    PROP_BACKUP_AND_RESTORE_STATE,
#if ( BACNET_SVC_COV_B == 1 )
    PROP_ACTIVE_COV_SUBSCRIPTIONS,
#endif
#if ( BACNET_PROTOCOL_REVISION < 17 )
    PROP_SLAVE_PROXY_ENABLE,        // todo, only allowed in some cases - moved to Port Object at Rev 17
#endif
    PROP_MANUAL_SLAVE_ADDRESS_BINDING,
    PROP_AUTO_SLAVE_DISCOVERY,
    PROP_SLAVE_ADDRESS_BINDING,
    PROP_LAST_RESTART_REASON,
    PROP_TIME_OF_DEVICE_RESTART,
    PROP_RESTART_NOTIFICATION_RECIPIENTS,
    PROP_UTC_TIME_SYNCHRONIZATION_RECIPIENTS,
    PROP_TIME_SYNCHRONIZATION_INTERVAL,
    PROP_ALIGN_INTERVALS,
    PROP_INTERVAL_OFFSET,
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};


#if 0
        protected static PROPERTY_ID[] Access_Door_Properties_Required = new PROPERTY_ID[] {
            PROPERTY_ID.PRESENT_VALUE,
            PROPERTY_ID.GLOBAL_IDENTIFIER,
            PROPERTY_ID.OCCUPANCY_STATE,
            PROPERTY_ID.STATUS_FLAGS,
            PROPERTY_ID.EVENT_STATE,
            PROPERTY_ID.RELIABILITY,
            PROPERTY_ID.OUT_OF_SERVICE,
            PROPERTY_ID.PRIORITY_ARRAY,
            PROPERTY_ID.RELINQUISH_DEFAULT,
            PROPERTY_ID.DOOR_PULSE_TIME,
            PROPERTY_ID.DOOR_EXTENDED_PULSE_TIME,
            PROPERTY_ID.DOOR_OPEN_TOO_LONG_TIME,
            PROPERTY_ID.CURRENT_COMMAND_PRIORITY,
        };


        protected static PROPERTY_ID[] Access_Door_Properties_Optional = new PROPERTY_ID[] {
            PROPERTY_ID.DESCRIPTION,
            PROPERTY_ID.DOOR_STATUS,
            PROPERTY_ID.LOCK_STATUS,
            PROPERTY_ID.SECURED_STATUS,
            PROPERTY_ID.DOOR_MEMBERS,
            PROPERTY_ID.DOOR_UNLOCK_DELAY_TIME,
            PROPERTY_ID.DOOR_ALARM_STATE,
            PROPERTY_ID.MASKED_ALARM_VALUES,
            PROPERTY_ID.MAINTENANCE_REQUIRED,
            PROPERTY_ID.TIME_DELAY,
            PROPERTY_ID.NOTIFICATION_CLASS,
            PROPERTY_ID.ALARM_VALUES,
            PROPERTY_ID.FAULT_VALUES,
            PROPERTY_ID.EVENT_ENABLE,
            PROPERTY_ID.ACKED_TRANSITIONS,
            PROPERTY_ID.NOTIFY_TYPE,
            PROPERTY_ID.EVENT_TIME_STAMPS,
            PROPERTY_ID.EVENT_MESSAGE_TEXTS,
            PROPERTY_ID.EVENT_MESSAGE_TEXTS_CONFIG,
            PROPERTY_ID.EVENT_DETECTION_ENABLE,
            PROPERTY_ID.EVENT_ALGORITHM_INHIBIT_REF,
            PROPERTY_ID.EVENT_ALGORITHM_INHIBIT,
            PROPERTY_ID.TIME_DELAY_NORMAL,
            PROPERTY_ID.RELIABILITY_EVALUATION_INHIBIT,
            PROPERTY_ID.VALUE_SOURCE,
            PROPERTY_ID.VALUE_SOURCE_ARRAY,
            PROPERTY_ID.LAST_COMMAND_TIME,
            PROPERTY_ID.COMMAND_TIME_ARRAY,
            PROPERTY_ID.TAGS,
            PROPERTY_ID.PROFILE_LOCATION,
            PROPERTY_ID.PROFILE_NAME,
        };


        protected static PROPERTY_ID[] Access_Zone_Properties_Required = new PROPERTY_ID[] {
            PROPERTY_ID.GLOBAL_IDENTIFIER,
            PROPERTY_ID.OCCUPANCY_STATE,
            PROPERTY_ID.STATUS_FLAGS,
            PROPERTY_ID.EVENT_STATE,
            PROPERTY_ID.RELIABILITY,
            PROPERTY_ID.OUT_OF_SERVICE,
            PROPERTY_ID.ENTRY_POINTS,
            PROPERTY_ID.EXIT_POINTS,
        };

        protected static PROPERTY_ID[] Access_Zone_Properties_Optional = new PROPERTY_ID[] {
            PROPERTY_ID.DESCRIPTION,
            PROPERTY_ID.OCCUPANCY_COUNT,
            PROPERTY_ID.OCCUPANCY_COUNT_ENABLE,
            PROPERTY_ID.ADJUST_VALUE,
            PROPERTY_ID.OCCUPANCY_UPPER_LIMIT,
            PROPERTY_ID.OCCUPANCY_LOWER_LIMIT,
            PROPERTY_ID.CREDENTIALS_IN_ZONE,
            PROPERTY_ID.LAST_CREDENTIAL_ADDED,
            PROPERTY_ID.LAST_CREDENTIAL_ADDED_TIME,
            PROPERTY_ID.LAST_CREDENTIAL_REMOVED,
            PROPERTY_ID.LAST_CREDENTIAL_REMOVED_TIME,
            PROPERTY_ID.PASSBACK_MODE,
            PROPERTY_ID.PASSBACK_TIMEOUT,
            PROPERTY_ID.TIME_DELAY,
            PROPERTY_ID.NOTIFICATION_CLASS,
            PROPERTY_ID.ALARM_VALUES,
            PROPERTY_ID.EVENT_ENABLE,
            PROPERTY_ID.ACKED_TRANSITIONS,
            PROPERTY_ID.NOTIFY_TYPE,
            PROPERTY_ID.EVENT_TIME_STAMPS,
            PROPERTY_ID.EVENT_MESSAGE_TEXTS,
            PROPERTY_ID.EVENT_MESSAGE_TEXTS_CONFIG,
            PROPERTY_ID.EVENT_DETECTION_ENABLE,
            PROPERTY_ID.EVENT_ALGORITHM_INHIBIT_REF,
            PROPERTY_ID.EVENT_ALGORITHM_INHIBIT,
            PROPERTY_ID.TIME_DELAY_NORMAL,
            PROPERTY_ID.RELIABILITY_EVALUATION_INHIBIT,
            PROPERTY_ID.TAGS,
            PROPERTY_ID.PROFILE_LOCATION,
            PROPERTY_ID.PROFILE_NAME
        };

#endif

static const BACNET_PROPERTY_ID Accumulator_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_STATUS_FLAGS,
    PROP_EVENT_STATE,
    PROP_OUT_OF_SERVICE,
    PROP_SCALE,
    PROP_UNITS,
    PROP_MAX_PRES_VALUE,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Accumulator_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_DEVICE_TYPE,
    PROP_RELIABILITY,
    PROP_PRESCALE,
    PROP_VALUE_CHANGE_TIME,
    PROP_VALUE_BEFORE_CHANGE,
    PROP_VALUE_SET,
    PROP_LOGGING_RECORD,
    PROP_LOGGING_OBJECT,
    PROP_PULSE_RATE,
    PROP_HIGH_LIMIT,
    PROP_LOW_LIMIT,
    PROP_LIMIT_MONITORING_INTERVAL,
    PROP_NOTIFICATION_CLASS,
    PROP_TIME_DELAY,
    PROP_LIMIT_ENABLE,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
    PROP_PROFILE_NAME,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    PROP_EVENT_DETECTION_ENABLE,
#endif
    MAX_BACNET_PROPERTY_ID
};

#if ( BACNET_USE_OBJECT_ALERT_ENROLLMENT )

static const BACNET_PROPERTY_ID Alert_Enrollment_Properties_Required[] = {

    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_EVENT_STATE,
    PROP_EVENT_DETECTION_ENABLE,
    PROP_NOTIFICATION_CLASS,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_PROPERTY_LIST,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Alert_Enrollment_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_EVENT_MESSAGE_TEXTS,
    PROP_EVENT_MESSAGE_TEXTS_CONFIG,
    PROP_EVENT_ALGORITHM_INHIBIT_REF,
    PROP_EVENT_ALGORITHM_INHIBIT,
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

#endif

static const BACNET_PROPERTY_ID Analog_Input_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_STATUS_FLAGS,
    PROP_EVENT_STATE,
    PROP_OUT_OF_SERVICE,
    PROP_UNITS,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Analog_Input_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_DEVICE_TYPE,
    PROP_RELIABILITY,
    PROP_UPDATE_INTERVAL,
    PROP_MIN_PRES_VALUE,
    PROP_MAX_PRES_VALUE,
    PROP_RESOLUTION,
    PROP_COV_INCREMENT,
    PROP_TIME_DELAY,
    PROP_NOTIFICATION_CLASS,
    PROP_HIGH_LIMIT,
    PROP_LOW_LIMIT,
    PROP_DEADBAND,
    PROP_LIMIT_ENABLE,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    PROP_EVENT_DETECTION_ENABLE,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Analog_Output_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_STATUS_FLAGS,
    PROP_EVENT_STATE,
    PROP_OUT_OF_SERVICE,
    PROP_UNITS,
    PROP_PRIORITY_ARRAY,
    PROP_RELINQUISH_DEFAULT,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Analog_Output_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_DEVICE_TYPE,
    PROP_RELIABILITY,
    PROP_MIN_PRES_VALUE,
    PROP_MAX_PRES_VALUE,
    PROP_RESOLUTION,
    PROP_COV_INCREMENT,
    PROP_TIME_DELAY,
    PROP_NOTIFICATION_CLASS,
    PROP_HIGH_LIMIT,
    PROP_LOW_LIMIT,
    PROP_DEADBAND,
    PROP_LIMIT_ENABLE,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    PROP_EVENT_DETECTION_ENABLE,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Analog_Value_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_STATUS_FLAGS,
    PROP_EVENT_STATE,
    PROP_OUT_OF_SERVICE,
    PROP_UNITS,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Analog_Value_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_RELIABILITY,
    PROP_PRIORITY_ARRAY,
    PROP_RELINQUISH_DEFAULT,
    PROP_COV_INCREMENT,
    PROP_TIME_DELAY,
    PROP_NOTIFICATION_CLASS,
    PROP_HIGH_LIMIT,
    PROP_LOW_LIMIT,
    PROP_DEADBAND,
    PROP_LIMIT_ENABLE,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    PROP_EVENT_DETECTION_ENABLE,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Averaging_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_MINIMUM_VALUE,
    PROP_AVERAGE_VALUE,
    PROP_MAXIMUM_VALUE,
    PROP_STATUS_FLAGS,
    PROP_EVENT_STATE,
    PROP_OUT_OF_SERVICE,
    PROP_UNITS,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Averaging_Properties_Optional[] = {
    PROP_PROFILE_NAME,
    PROP_MINIMUM_VALUE_TIMESTAMP,
    PROP_VARIANCE_VALUE,
    PROP_MAXIMUM_VALUE_TIMESTAMP,
    PROP_DESCRIPTION,
    PROP_ATTEMPTED_SAMPLES,
    PROP_VALID_SAMPLES,
    PROP_OBJECT_PROPERTY_REFERENCE,
    PROP_WINDOW_INTERVAL,
    PROP_WINDOW_SAMPLES,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Binary_Input_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_STATUS_FLAGS,
    PROP_EVENT_STATE,
    PROP_OUT_OF_SERVICE,
    PROP_POLARITY,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Binary_Input_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_DEVICE_TYPE,
    PROP_RELIABILITY,
    PROP_INACTIVE_TEXT,
    PROP_ACTIVE_TEXT,
    PROP_CHANGE_OF_STATE_TIME,
    PROP_CHANGE_OF_STATE_COUNT,
    PROP_TIME_OF_STATE_COUNT_RESET,
    PROP_ELAPSED_ACTIVE_TIME,
    PROP_TIME_OF_ACTIVE_TIME_RESET,
    PROP_TIME_DELAY,
    PROP_NOTIFICATION_CLASS,
    PROP_ALARM_VALUE,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    PROP_EVENT_DETECTION_ENABLE,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Binary_Output_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_STATUS_FLAGS,
    PROP_EVENT_STATE,
    PROP_OUT_OF_SERVICE,
    PROP_POLARITY,
    PROP_PRIORITY_ARRAY,
    PROP_RELINQUISH_DEFAULT,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Binary_Output_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_DEVICE_TYPE,
    PROP_RELIABILITY,
    PROP_INACTIVE_TEXT,
    PROP_ACTIVE_TEXT,
    PROP_CHANGE_OF_STATE_TIME,
    PROP_CHANGE_OF_STATE_COUNT,
    PROP_TIME_OF_STATE_COUNT_RESET,
    PROP_ELAPSED_ACTIVE_TIME,
    PROP_TIME_OF_ACTIVE_TIME_RESET,
    PROP_MINIMUM_OFF_TIME,
    PROP_MINIMUM_ON_TIME,
    PROP_TIME_DELAY,
    PROP_NOTIFICATION_CLASS,
    PROP_FEEDBACK_VALUE,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    PROP_EVENT_DETECTION_ENABLE,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Binary_Value_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_STATUS_FLAGS,
    PROP_EVENT_STATE,
    PROP_OUT_OF_SERVICE,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Binary_Value_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_RELIABILITY,
    PROP_INACTIVE_TEXT,
    PROP_ACTIVE_TEXT,
    PROP_CHANGE_OF_STATE_TIME,
    PROP_CHANGE_OF_STATE_COUNT,
    PROP_TIME_OF_STATE_COUNT_RESET,
    PROP_ELAPSED_ACTIVE_TIME,
    PROP_TIME_OF_ACTIVE_TIME_RESET,
    PROP_MINIMUM_OFF_TIME,
    PROP_MINIMUM_ON_TIME,
    PROP_PRIORITY_ARRAY,
    PROP_RELINQUISH_DEFAULT,
    PROP_TIME_DELAY,
    PROP_NOTIFICATION_CLASS,
    PROP_ALARM_VALUE,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    PROP_EVENT_DETECTION_ENABLE,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Calendar_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_DATE_LIST,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Calendar_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

#if ( BACNET_PROTOCOL_REVISION >= 14 )
static const BACNET_PROPERTY_ID Channel_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_LAST_PRIORITY,
    PROP_WRITE_STATUS,
    PROP_STATUS_FLAGS,
    PROP_OUT_OF_SERVICE,
    PROP_LIST_OF_OBJECT_PROPERTY_REFERENCES,
    PROP_CHANNEL_NUMBER,
    PROP_CONTROL_GROUPS,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Channel_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_RELIABILITY,
    PROP_EXECUTION_DELAY,
    PROP_ALLOW_GROUP_DELAY_INHIBIT,
    PROP_EVENT_DETECTION_ENABLE,
    PROP_NOTIFICATION_CLASS,
    PROP_EVENT_ENABLE,
    PROP_EVENT_STATE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
    PROP_EVENT_MESSAGE_TEXTS_CONFIG,
    PROP_RELIABILITY_EVALUATION_INHIBIT,
    PROP_EXECUTION_DELAY,
    PROP_ALLOW_GROUP_DELAY_INHIBIT,
    PROP_EVENT_DETECTION_ENABLE,
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};
#endif // ( BACNET_PROTOCOL_REVISION >= 14 )

static const BACNET_PROPERTY_ID Command_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_IN_PROCESS,
    PROP_ALL_WRITES_SUCCESSFUL,
    PROP_ACTION,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Command_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_ACTION_TEXT,
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID CharacterString_Value_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_STATUS_FLAGS,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID CharacterString_Value_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_EVENT_STATE,
    PROP_RELIABILITY,
    PROP_OUT_OF_SERVICE,
    PROP_PRIORITY_ARRAY,
    PROP_RELINQUISH_DEFAULT,
    PROP_TIME_DELAY,
    PROP_NOTIFICATION_CLASS,
    PROP_ALARM_VALUES,
    PROP_FAULT_VALUES,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    PROP_EVENT_DETECTION_ENABLE,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

#if (BACNET_PROTOCOL_REVISION >= 14)
static const BACNET_PROPERTY_ID Lighting_Output_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_TRACKING_VALUE,
    PROP_LIGHTING_COMMAND,
    PROP_IN_PROGRESS,
    PROP_STATUS_FLAGS,
    PROP_OUT_OF_SERVICE,
    PROP_BLINK_WARN_ENABLE,
    PROP_EGRESS_TIME,
    PROP_EGRESS_ACTIVE,
    PROP_DEFAULT_FADE_TIME,
    PROP_DEFAULT_RAMP_RATE,
    PROP_DEFAULT_STEP_INCREMENT,
    PROP_PRIORITY_ARRAY,
    PROP_RELINQUISH_DEFAULT,
    PROP_LIGHTING_COMMAND_DEFAULT_PRIORITY,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Lighting_Output_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_RELIABILITY,
    PROP_TRANSITION,
    PROP_FEEDBACK_VALUE,
    PROP_POWER,
    PROP_INSTANTANEOUS_POWER,
    PROP_MIN_ACTUAL_VALUE,
    PROP_MAX_ACTUAL_VALUE,
    PROP_COV_INCREMENT,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};
#endif // ( BACNET_PROTOCOL_REVISION >= 14 )

static const BACNET_PROPERTY_ID Load_Control_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_STATUS_FLAGS,
    PROP_EVENT_STATE,
    PROP_REQUESTED_SHED_LEVEL,
    PROP_START_TIME,
    PROP_SHED_DURATION,
    PROP_DUTY_WINDOW,
    PROP_ENABLE,
    PROP_EXPECTED_SHED_LEVEL,
    PROP_ACTUAL_SHED_LEVEL,
    PROP_SHED_LEVELS,
    PROP_SHED_LEVEL_DESCRIPTIONS,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Load_Control_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_STATE_DESCRIPTION,
    PROP_RELIABILITY,
    PROP_FULL_DUTY_BASELINE,
    PROP_NOTIFICATION_CLASS,
    PROP_TIME_DELAY,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Life_Safety_Point_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_TRACKING_VALUE,
    PROP_STATUS_FLAGS,
    PROP_EVENT_STATE,
    PROP_OUT_OF_SERVICE,
    PROP_RELIABILITY,
    PROP_MODE,
    PROP_ACCEPTED_MODES,
    PROP_SILENCED,
    PROP_OPERATION_EXPECTED,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Life_Safety_Point_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_DEVICE_TYPE,
    PROP_NOTIFICATION_CLASS,
    PROP_LIFE_SAFETY_ALARM_VALUES,
    PROP_ALARM_VALUES,
    PROP_FAULT_VALUES,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
    PROP_MAINTENANCE_REQUIRED,
    PROP_SETTING,
    PROP_DIRECT_READING,
    PROP_UNITS,
    PROP_MEMBER_OF,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

#if 0 // from BTC
        protected static PROPERTY_ID[] Loop_Properties_Required = new PROPERTY_ID[] {
            PROPERTY_ID.PRESENT_VALUE,
            PROPERTY_ID.STATUS_FLAGS,
            PROPERTY_ID.EVENT_STATE,
            PROPERTY_ID.OUT_OF_SERVICE,
            PROPERTY_ID.OUTPUT_UNITS,
            PROPERTY_ID.MANIPULATED_VARIABLE_REFERENCE,
            PROPERTY_ID.CONTROLLED_VARIABLE_REFERENCE,
            PROPERTY_ID.CONTROLLED_VARIABLE_VALUE,
            PROPERTY_ID.DERIVATIVE_CONSTANT_UNITS,
            PROPERTY_ID.SETPOINT_REFERENCE,
            PROPERTY_ID.SETPOINT,
            PROPERTY_ID.ACTION,
            PROPERTY_ID.PRIORITY_FOR_WRITING,

            };

        private static List<BACNET_PROPERTY_ID> Loop_Properties_Optional = new List<BACNET_PROPERTY_ID>()
        {
            new BACNET_PROPERTY_ID ( PROPERTY_ID.DESCRIPTION),
            new BACNET_PROPERTY_ID ( PROPERTY_ID.RELIABILITY),
            new BACNET_PROPERTY_ID ( PROPERTY_ID.PROFILE_NAME),
            new BACNET_PROPERTY_ID ( PROPERTY_ID.COV_INCREMENT, expectedDataType:typeof(BACnetDatatypeReal) ),
            new BACNET_PROPERTY_ID ( PROPERTY_ID.DEADBAND, expectedDataType:typeof(BACnetDatatypeReal) ),
            PROPERTY_ID.UPDATE_INTERVAL
            PROPERTY_ID.PROPORTIONAL_CONSTANT
            PROPERTY_ID.PROPORTIONAL_CONSTANT_UNITS
            PROPERTY_ID.INTEGRAL_CONSTANT
            PROPERTY_ID.INTEGRAL_CONSTANT_UNITS
            PROPERTY_ID.DERIVATIVE_CONSTANT
            PROPERTY_ID.DERIVATIVE_CONSTANT_UNITS
            PROPERTY_ID.BIAS
            PROPERTY_ID.MAXIMUM_OUTPUT
            PROPERTY_ID.MINIMUM_OUTPUT
            PROPERTY_ID.COV_INCREMENT
            PROPERTY_ID.TIME_DELAY
            PROPERTY_ID.NOTIFICATION_CLASS
            PROPERTY_ID.ERROR_LIMIT
            PROPERTY_ID.DEADBAND
            PROPERTY_ID.EVENT_ENABLE
            PROPERTY_ID.ACKED_TRANSITIONS
            PROPERTY_ID.NOTIFY_TYPE
            PROPERTY_ID.EVENT_TIME_STAMPS
            PROPERTY_ID.EVENT_MESSAGE_TEXTS
            PROPERTY_ID.EVENT_MESSAGE_TEXTS_CONFIG
            PROPERTY_ID.EVENT_DETECTION_ENABLE
            PROPERTY_ID.EVENT_ALGORITHM_INHIBIT
            PROPERTY_ID.EVENT_ALGORITHM_INHIBIT_REF
            PROPERTY_ID.TIME_DELAY_NORMAL
            PROPERTY_ID.LOW_DIFF_LIMIT
            PROPERTY_ID.TAGS
            PROPERTY_ID.PROFILE_LOCATION
            PROPERTY_ID.PROFILE_NAME
        };
#endif

static const BACNET_PROPERTY_ID Multistate_Input_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_STATUS_FLAGS,
    PROP_EVENT_STATE,
    PROP_OUT_OF_SERVICE,
    PROP_NUMBER_OF_STATES,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Multistate_Input_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_DEVICE_TYPE,
    PROP_RELIABILITY,
    PROP_STATE_TEXT,
    PROP_TIME_DELAY,
    PROP_NOTIFICATION_CLASS,
    PROP_ALARM_VALUES,
    PROP_FAULT_VALUES,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    PROP_EVENT_DETECTION_ENABLE,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Multistate_Output_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_STATUS_FLAGS,
    PROP_EVENT_STATE,
    PROP_OUT_OF_SERVICE,
    PROP_NUMBER_OF_STATES,
    PROP_PRIORITY_ARRAY,
    PROP_RELINQUISH_DEFAULT,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Multistate_Output_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_DEVICE_TYPE,
    PROP_RELIABILITY,
    PROP_STATE_TEXT,
    PROP_TIME_DELAY,
    PROP_NOTIFICATION_CLASS,
    PROP_FEEDBACK_VALUE,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    PROP_EVENT_DETECTION_ENABLE,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Multistate_Value_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_STATUS_FLAGS,
    PROP_EVENT_STATE,
    PROP_OUT_OF_SERVICE,
    PROP_NUMBER_OF_STATES,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Multistate_Value_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_RELIABILITY,
    PROP_STATE_TEXT,
    PROP_PRIORITY_ARRAY,
    PROP_RELINQUISH_DEFAULT,
    PROP_TIME_DELAY,
    PROP_NOTIFICATION_CLASS,
    PROP_ALARM_VALUES,
    PROP_FAULT_VALUES,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    PROP_EVENT_DETECTION_ENABLE,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

#if 0
        protected static PROPERTY_ID[] Network_Port_Properties_Required = new PROPERTY_ID[] {
            PROPERTY_ID.STATUS_FLAGS,
            PROPERTY_ID.RELIABILITY,
            PROPERTY_ID.OUT_OF_SERVICE,
            PROPERTY_ID.NETWORK_TYPE,
            PROPERTY_ID.PROTOCOL_LEVEL,
            PROPERTY_ID.NETWORK_NUMBER,
            PROPERTY_ID.NETWORK_NUMBER_QUALITY,
            PROPERTY_ID.CHANGES_PENDING,
            PROPERTY_ID.APDU_LENGTH,
            PROPERTY_ID.LINK_SPEED,
        };

        protected static PROPERTY_ID[] Network_Port_Properties_Optional = new PROPERTY_ID[] {
            PROPERTY_ID.DESCRIPTION,
            PROPERTY_ID.REFERENCE_PORT,
            PROPERTY_ID.COMMAND,
            PROPERTY_ID.MAC_ADDRESS,
            PROPERTY_ID.LINK_SPEEDS,
            PROPERTY_ID.LINK_SPEED_AUTONEGOTIATE,
            PROPERTY_ID.NETWORK_INTERFACE_NAME,
            PROPERTY_ID.BACNET_IP_MODE,
            PROPERTY_ID.IP_ADDRESS,
            PROPERTY_ID.BACNET_IP_UDP_PORT,
            PROPERTY_ID.IP_SUBNET_MASK,
            PROPERTY_ID.IP_DEFAULT_GATEWAY,
            PROPERTY_ID.BACNET_IP_MULTICAST_ADDRESS,
            PROPERTY_ID.IP_DNS_SERVER,
            PROPERTY_ID.IP_DHCP_ENABLE,
            PROPERTY_ID.IP_DHCP_LEASE_TIME,
            PROPERTY_ID.IP_DHCP_LEASE_TIME_REMAINING,
            PROPERTY_ID.IP_DHCP_SERVER,
            PROPERTY_ID.BACNET_IP_NAT_TRAVERSAL,
            PROPERTY_ID.BACNET_IP_GLOBAL_ADDRESS,
            PROPERTY_ID.BBMD_BROADCAST_DISTRIBUTION_TABLE,
            PROPERTY_ID.BBMD_ACCEPT_FD_REGISTRATIONS,
            PROPERTY_ID.BBMD_FOREIGN_DEVICE_TABLE,
            PROPERTY_ID.FD_BBMD_ADDRESS,
            PROPERTY_ID.FD_SUBSCRIPTION_LIFETIME,
            PROPERTY_ID.BACNET_IPV6_MODE,
            PROPERTY_ID.IPV6_ADDRESS,
            PROPERTY_ID.IPV6_PREFIX_LENGTH,
            PROPERTY_ID.BACNET_IPV6_UDP_PORT,
            PROPERTY_ID.IPV6_DEFAULT_GATEWAY,
            PROPERTY_ID.BACNET_IPV6_MULTICAST_ADDRESS,
            PROPERTY_ID.IPV6_DNS_SERVER,
            PROPERTY_ID.IPV6_AUTO_ADDRESSING_ENABLE,
            PROPERTY_ID.IPV6_DHCP_LEASE_TIME,
            PROPERTY_ID.IPV6_DHCP_LEASE_TIME_REMAINING,
            PROPERTY_ID.IPV6_DHCP_SERVER,
            PROPERTY_ID.IPV6_ZONE_INDEX,
            PROPERTY_ID.MAX_MASTER,
            PROPERTY_ID.MAX_INFO_FRAMES,
            PROPERTY_ID.SLAVE_PROXY_ENABLE,
            PROPERTY_ID.MANUAL_SLAVE_ADDRESS_BINDING,
            PROPERTY_ID.AUTO_SLAVE_DISCOVERY,
            PROPERTY_ID.SLAVE_ADDRESS_BINDING,
            PROPERTY_ID.VIRTUAL_MAC_ADDRESS_TABLE,
            PROPERTY_ID.ROUTING_TABLE,
            PROPERTY_ID.EVENT_DETECTION_ENABLE,
            PROPERTY_ID.NOTIFICATION_CLASS,
            PROPERTY_ID.EVENT_ENABLE,
            PROPERTY_ID.ACKED_TRANSITIONS,
            PROPERTY_ID.NOTIFY_TYPE,
            PROPERTY_ID.EVENT_TIME_STAMPS,
            PROPERTY_ID.EVENT_MESSAGE_TEXTS,
            PROPERTY_ID.EVENT_MESSAGE_TEXTS_CONFIG,
            PROPERTY_ID.EVENT_STATE,
            PROPERTY_ID.RELIABILITY_EVALUATION_INHIBIT,
            PROPERTY_ID.TAGS,
            PROPERTY_ID.PROFILE_LOCATION,
            PROPERTY_ID.PROFILE_NAME
        };


#endif

static const BACNET_PROPERTY_ID Notification_Class_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_NOTIFICATION_CLASS,
    PROP_PRIORITY,
    PROP_ACK_REQUIRED,
    PROP_RECIPIENT_LIST,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Notification_Class_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

#ifdef todo
    // from BTC
        protected static PROPERTY_ID[] Octectstring_Value_Properties_Required = new PROPERTY_ID[] {
            PROPERTY_ID.PRESENT_VALUE,
            PROPERTY_ID.STATUS_FLAGS,
        };


        protected static PROPERTY_ID[] Octectstring_Value_Properties_Optional = new PROPERTY_ID[] {
            PROPERTY_ID.DESCRIPTION,
            PROPERTY_ID.EVENT_DETECTION_ENABLE,
            PROPERTY_ID.RELIABILITY,
            PROPERTY_ID.PRIORITY_ARRAY,
            PROPERTY_ID.OUT_OF_SERVICE,
            PROPERTY_ID.RELINQUISH_DEFAULT,
            PROPERTY_ID.COV_INCREMENT,
            PROPERTY_ID.TIME_DELAY,
            PROPERTY_ID.NOTIFICATION_CLASS,
            PROPERTY_ID.HIGH_LIMIT,
            PROPERTY_ID.LOW_LIMIT,
            PROPERTY_ID.DEADBAND,
            PROPERTY_ID.LIMIT_ENABLE,
            PROPERTY_ID.EVENT_ENABLE,
            PROPERTY_ID.EVENT_STATE,
            PROPERTY_ID.ACKED_TRANSITIONS,
            PROPERTY_ID.NOTIFY_TYPE,
            PROPERTY_ID.EVENT_TIME_STAMPS,
            PROPERTY_ID.EVENT_MESSAGE_TEXTS,
            PROPERTY_ID.RELIABILITY_EVALUATION_INHIBIT,
            PROPERTY_ID.PROFILE_NAME,
            // i just cut&pasted the above from Large_Integer_Value - revisit!
    };

        protected static PROPERTY_ID[] Positive_Integer_Value_Properties_Required = new PROPERTY_ID[] {
        PROPERTY_ID.PRESENT_VALUE,
        PROPERTY_ID.STATUS_FLAGS,
        PROPERTY_ID.UNITS,
    };


        protected static PROPERTY_ID[] Positive_Integer_Value_Properties_Optional = new PROPERTY_ID[] {
            PROPERTY_ID.DESCRIPTION,
            PROPERTY_ID.EVENT_DETECTION_ENABLE,
            PROPERTY_ID.RELIABILITY,
            PROPERTY_ID.PRIORITY_ARRAY,
            PROPERTY_ID.OUT_OF_SERVICE,
            PROPERTY_ID.RELINQUISH_DEFAULT,
            PROPERTY_ID.COV_INCREMENT,
            PROPERTY_ID.TIME_DELAY,
            PROPERTY_ID.NOTIFICATION_CLASS,
            PROPERTY_ID.HIGH_LIMIT,
            PROPERTY_ID.LOW_LIMIT,
            PROPERTY_ID.DEADBAND,
            PROPERTY_ID.LIMIT_ENABLE,
            PROPERTY_ID.EVENT_ENABLE,
            PROPERTY_ID.EVENT_STATE,
            PROPERTY_ID.ACKED_TRANSITIONS,
            PROPERTY_ID.NOTIFY_TYPE,
            PROPERTY_ID.EVENT_TIME_STAMPS,
            PROPERTY_ID.EVENT_MESSAGE_TEXTS,
            PROPERTY_ID.RELIABILITY_EVALUATION_INHIBIT,
            PROPERTY_ID.PROFILE_NAME,
/*
 * todo - add the rest... build a parser for bacnet spec??
        Event_Message_Texts_Config BACnetARRAY[3] of CharacterString O6
        Event_Algorithm_Inhibit_Ref BACnetObjectPropertyReference O6
        Event_Algorithm_Inhibit BOOLEAN O6,7
        Time_Delay_Normal Unsigned O6
        Min_Pres_Value Unsigned O
        Max_Pres_Value Unsigned O
        Resolution Unsigned O
        Property_List BACnetARRAY[N] of BACnetPropertyIdentifier R
        Fault_High_Limit Unsigned O9
        Fault_Low_Limit Unsigned O9
        Current_Command_Priority BACnetOptionalUnsigned O2
        Value_Source BACnetValueSource O10,12,14
        Value_Source_Array BACnetARRAY[16] of BACnetValueSource O11,13
        Last_Command_Time BACnetTimeStamp O11,13
        Command_Time_Array BACnetARRAY[16] of BACnetTimeStamp O13
        Tags BACnetARRAY[N] of BACnetNameValue O
        Profile_Location CharacterString O
*/
    };
        protected static PROPERTY_ID[] Schedule_Properties_Required = new PROPERTY_ID[] {
            PROPERTY_ID.OBJECT_IDENTIFIER,
            PROPERTY_ID.OBJECT_NAME,
            PROPERTY_ID.OBJECT_TYPE,
            PROPERTY_ID.PRESENT_VALUE,
            PROPERTY_ID.EFFECTIVE_PERIOD,
            PROPERTY_ID.WEEKLY_SCHEDULE,
            PROPERTY_ID.SCHEDULE_DEFAULT,
            PROPERTY_ID.LIST_OF_OBJECT_PROPERTY_REFERENCES,
            PROPERTY_ID.PRIORITY_FOR_WRITING,
            PROPERTY_ID.STATUS_FLAGS,
            PROPERTY_ID.RELIABILITY,
            PROPERTY_ID.OUT_OF_SERVICE,
            PROPERTY_ID.PROPERTY_LIST,
            };

        protected static PROPERTY_ID[] Schedule_Properties_Optional = new PROPERTY_ID[] {
            PROPERTY_ID.DESCRIPTION,
            PROPERTY_ID.EXCEPTION_SCHEDULE,
            PROPERTY_ID.EVENT_DETECTION_ENABLE,
            PROPERTY_ID.NOTIFICATION_CLASS,
            PROPERTY_ID.EVENT_ENABLE,
            PROPERTY_ID.EVENT_STATE,
            PROPERTY_ID.ACKED_TRANSITIONS,
            PROPERTY_ID.NOTIFY_TYPE,
            PROPERTY_ID.EVENT_TIME_STAMPS,
            PROPERTY_ID.EVENT_MESSAGE_TEXTS,
            PROPERTY_ID.EVENT_MESSAGE_TEXTS_CONFIG,
            PROPERTY_ID.RELIABILITY_EVALUATION_INHIBIT,
            PROPERTY_ID.PROFILE_NAME,
            };
#endif


static const BACNET_PROPERTY_ID Trend_Log_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_ENABLE,
    PROP_STOP_WHEN_FULL,
    PROP_BUFFER_SIZE,
    PROP_LOG_BUFFER,
    PROP_RECORD_COUNT,
    PROP_TOTAL_RECORD_COUNT,
    PROP_EVENT_STATE,
    PROP_LOGGING_TYPE,
    PROP_STATUS_FLAGS,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Trend_Log_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_START_TIME,
    PROP_STOP_TIME,
    PROP_LOG_DEVICE_OBJECT_PROPERTY,
    PROP_LOG_INTERVAL,
    PROP_COV_RESUBSCRIPTION_INTERVAL,
    PROP_CLIENT_COV_INCREMENT,
    PROP_NOTIFICATION_THRESHOLD,
    PROP_RECORDS_SINCE_NOTIFICATION,
    PROP_LAST_NOTIFY_RECORD,
    PROP_NOTIFICATION_CLASS,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
    PROP_ALIGN_INTERVALS,
    PROP_INTERVAL_OFFSET,
    PROP_TRIGGER,
    PROP_RELIABILITY,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    PROP_EVENT_DETECTION_ENABLE,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID File_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_FILE_TYPE,
    PROP_FILE_SIZE,
    PROP_MODIFICATION_DATE,
    PROP_ARCHIVE,
    PROP_READ_ONLY,
    PROP_FILE_ACCESS_METHOD,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID File_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_RECORD_COUNT,
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

/* These three arrays are used by the ReadPropertyMultiple handler */
static const BACNET_PROPERTY_ID Integer_Value_Properties_Required[] = {
    PROP_OBJECT_IDENTIFIER,
    PROP_OBJECT_NAME,
    PROP_OBJECT_TYPE,
    PROP_PRESENT_VALUE,
    PROP_STATUS_FLAGS,
    PROP_UNITS,
    MAX_BACNET_PROPERTY_ID
};

static const BACNET_PROPERTY_ID Integer_Value_Properties_Optional[] = {
    PROP_DESCRIPTION,
    PROP_EVENT_STATE,
    PROP_RELIABILITY,
    PROP_OUT_OF_SERVICE,
    PROP_PRIORITY_ARRAY,
    PROP_RELINQUISH_DEFAULT,
    PROP_COV_INCREMENT,
    PROP_TIME_DELAY,
    PROP_NOTIFICATION_CLASS,
    PROP_HIGH_LIMIT,
    PROP_LOW_LIMIT,
    PROP_DEADBAND,
    PROP_LIMIT_ENABLE,
    PROP_EVENT_ENABLE,
    PROP_ACKED_TRANSITIONS,
    PROP_NOTIFY_TYPE,
    PROP_EVENT_TIME_STAMPS,
    PROP_EVENT_MESSAGE_TEXTS,
#if ( BACNET_PROTOCOL_REVISION >= 13 )
    PROP_EVENT_MESSAGE_TEXTS_CONFIG,
    PROP_EVENT_DETECTION_ENABLE,
    PROP_EVENT_ALGORITHM_INHIBIT_REF,
    PROP_EVENT_ALGORITHM_INHIBIT,
    PROP_TIME_DELAY_NORMAL,
    PROP_RELIABILITY_EVALUATION_INHIBIT,
#endif
    PROP_MIN_PRES_VALUE,
    PROP_MAX_PRES_VALUE,
    PROP_RESOLUTION,
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    PROP_EVENT_DETECTION_ENABLE,
#endif
    PROP_PROFILE_NAME,
    MAX_BACNET_PROPERTY_ID
};

#endif

/**
 * Function that returns the number of BACnet object properties in a list
 *
 * @param pList - array of type 'int' that is a list of BACnet object
 * properties, terminated by a '-1' value.
 */
unsigned property_list_count(
    const BACNET_PROPERTY_ID *pList)
{
    unsigned property_count = 0;

    if (pList) {
        while (*pList != MAX_BACNET_PROPERTY_ID) {
            property_count++;
            pList++;
        }
    }

    return property_count;
}

#if ( BACNET_PROPERTY_LISTS == 1 )

/**
 * Function that returns the list of all Optional properties
 * of known standard objects.
 *
 * @param object_type - enumerated BACNET_OBJECT_TYPE
 * @return returns a pointer to a 'MAX_BACNET_PROPERTY_ID' terminated array of
 * type 'int' that contain BACnet object properties for the given object
 * type.
 */
const BACNET_PROPERTY_ID * property_list_optional(
    BACNET_OBJECT_TYPE object_type)
{
    const BACNET_PROPERTY_ID * pList = NULL;

    switch (object_type) {
    case OBJECT_DEVICE:
        pList = Device_Properties_Optional;
        break;
    case OBJECT_ACCUMULATOR:
        pList = Accumulator_Properties_Optional;
        break;
#if ( BACNET_USE_OBJECT_ALERT_ENROLLMENT )
    case OBJECT_ALERT_ENROLLMENT:
        pList = Alert_Enrollment_Properties_Optional;
        break;
#endif
    case OBJECT_ANALOG_INPUT:
        pList = Analog_Input_Properties_Optional;
        break;
    case OBJECT_ANALOG_OUTPUT:
        pList = Analog_Output_Properties_Optional;
        break;
    case OBJECT_ANALOG_VALUE:
        pList = Analog_Value_Properties_Optional;
        break;
    case OBJECT_AVERAGING:
        pList = Averaging_Properties_Optional;
        break;
    case OBJECT_BINARY_INPUT:
        pList = Binary_Input_Properties_Optional;
        break;
    case OBJECT_BINARY_OUTPUT:
        pList = Binary_Output_Properties_Optional;
        break;
    case OBJECT_BINARY_VALUE:
        pList = Binary_Value_Properties_Optional;
        break;
    case OBJECT_CALENDAR:
        pList = Calendar_Properties_Optional;
        break;
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    case OBJECT_CHANNEL:
        pList = Channel_Properties_Optional;
        break;
        case OBJECT_LIGHTING_OUTPUT:
            pList = Lighting_Output_Properties_Optional;
            break;
#endif
    case OBJECT_COMMAND:
        pList = Command_Properties_Optional;
        break;
    case OBJECT_CHARACTERSTRING_VALUE:
        pList =
            CharacterString_Value_Properties_Optional;
        break;
    case OBJECT_LOAD_CONTROL:
        pList = Load_Control_Properties_Optional;
        break;
    case OBJECT_LIFE_SAFETY_POINT:
        pList =
            Life_Safety_Point_Properties_Optional;
        break;
    case OBJECT_MULTI_STATE_INPUT:
        pList =
            Multistate_Input_Properties_Optional;
        break;
    case OBJECT_MULTI_STATE_OUTPUT:
        pList =
            Multistate_Output_Properties_Optional;
        break;
    case OBJECT_MULTI_STATE_VALUE:
        pList =
            Multistate_Value_Properties_Optional;
        break;
    case OBJECT_NOTIFICATION_CLASS:
        pList =
            Notification_Class_Properties_Optional;
        break;
    case OBJECT_TRENDLOG:
        pList = Trend_Log_Properties_Optional;
        break;
    case OBJECT_FILE:
        pList = File_Properties_Optional;
        break;
    case OBJECT_INTEGER_VALUE:
        pList = Integer_Value_Properties_Optional;
        break;
    default:
        break;
    }

    return pList;
}

/**
 * Function that returns the list of Required properties
 * of known standard objects.
 *
 * @param object_type - enumerated BACNET_OBJECT_TYPE
 * @return returns a pointer to a 'MAX_BACNET_PROPERTY_ID' terminated array of
 * type 'int' that contain BACnet object properties for the given object
 * type.
 */
const BACNET_PROPERTY_ID* property_list_required(
    BACNET_OBJECT_TYPE object_type)
{
    const BACNET_PROPERTY_ID * pList = NULL;

    switch (object_type) {
    case OBJECT_DEVICE:
        pList = Device_Properties_Required;
        break;
    case OBJECT_ACCUMULATOR:
        pList = Accumulator_Properties_Required;
        break;
#if ( BACNET_USE_OBJECT_ALERT_ENROLLMENT )
    case OBJECT_ALERT_ENROLLMENT:
        pList = Alert_Enrollment_Properties_Required;
        break;
#endif
    case OBJECT_ANALOG_INPUT:
        pList = Analog_Input_Properties_Required;
        break;
    case OBJECT_ANALOG_OUTPUT:
        pList = Analog_Output_Properties_Required;
        break;
    case OBJECT_ANALOG_VALUE:
        pList = Analog_Value_Properties_Required;
        break;
    case OBJECT_AVERAGING:
        pList = Averaging_Properties_Required;
        break;
    case OBJECT_BINARY_INPUT:
        pList = Binary_Input_Properties_Required;
        break;
    case OBJECT_BINARY_OUTPUT:
        pList = Binary_Output_Properties_Required;
        break;
    case OBJECT_BINARY_VALUE:
        pList = Binary_Value_Properties_Required;
        break;
    case OBJECT_CALENDAR:
        pList = Calendar_Properties_Required;
        break;
#if ( BACNET_PROTOCOL_REVISION >= 14 )
    case OBJECT_CHANNEL:
        pList = Channel_Properties_Required;
        break;
        case OBJECT_LIGHTING_OUTPUT:
            pList = Lighting_Output_Properties_Required;
            break;
#endif // ( BACNET_PROTOCOL_REVISION >= 14 )
    case OBJECT_COMMAND:
        pList = Command_Properties_Required;
        break;
    case OBJECT_CHARACTERSTRING_VALUE:
        pList =
            CharacterString_Value_Properties_Required;
        break;
    case OBJECT_LOAD_CONTROL:
        pList = Load_Control_Properties_Required;
        break;
    case OBJECT_LIFE_SAFETY_POINT:
        pList =
            Life_Safety_Point_Properties_Required;
        break;
    case OBJECT_MULTI_STATE_INPUT:
        pList =
            Multistate_Input_Properties_Required;
        break;
    case OBJECT_MULTI_STATE_OUTPUT:
        pList =
            Multistate_Output_Properties_Required;
        break;
    case OBJECT_MULTI_STATE_VALUE:
        pList =
            Multistate_Value_Properties_Required;
        break;
    case OBJECT_NOTIFICATION_CLASS:
        pList =
            Notification_Class_Properties_Required;
        break;
    case OBJECT_TRENDLOG:
        pList = Trend_Log_Properties_Required;
        break;
    case OBJECT_FILE:
        pList = File_Properties_Required;
        break;
    case OBJECT_INTEGER_VALUE:
        pList = Integer_Value_Properties_Required;
        break;
    default:
        pList = Default_Properties_Required;
        break;
    }

    return pList;
}

/**
 * Function that returns the list of Required or Optional properties
 * of known standard objects.
 *
 * @param object_type - enumerated BACNET_OBJECT_TYPE
 * @param pPropertyList - returns a pointer to two 'MAX_BACNET_PROPERTY_ID' terminated arrays of
 * type 'int' that contain BACnet object properties for the given object
 * type.
 */
void property_list_special(
    BACNET_OBJECT_TYPE object_type,
    struct special_property_list_t *pPropertyList)
{
    if (pPropertyList == NULL) {
        return;
    }
    pPropertyList->Required.pList = property_list_required(object_type);
    pPropertyList->Optional.pList = property_list_optional(object_type);
    pPropertyList->Proprietary.pList = NULL;
    /* Fetch the counts if available otherwise zero them */
    pPropertyList->Required.count =
        property_list_count(pPropertyList->Required.pList);
    pPropertyList->Optional.count =
        property_list_count(pPropertyList->Optional.pList);
    pPropertyList->Proprietary.count = 0;

}

BACNET_PROPERTY_ID property_list_special_property(
    BACNET_OBJECT_TYPE object_type,
    BACNET_PROPERTY_ID special_property,
    unsigned index)
{
    int property = MAX_BACNET_PROPERTY_ID;  /* return value */
    unsigned required, optional, proprietary;
    struct special_property_list_t PropertyList = { {0} };

    property_list_special(object_type, &PropertyList);
    required = PropertyList.Required.count;
    optional = PropertyList.Optional.count;
    proprietary = PropertyList.Proprietary.count;
    if (special_property == PROP_ALL) {
        if (index < required) {
            if (PropertyList.Required.pList) {
                property = PropertyList.Required.pList[index];
            }
        } else if (index < (required + optional)) {
            if (PropertyList.Optional.pList) {
                index -= required;
                property = PropertyList.Optional.pList[index];
            }
        } else if (index < (required + optional + proprietary)) {
            if (PropertyList.Proprietary.pList) {
                index -= (required + optional);
                property = PropertyList.Proprietary.pList[index];
            }
        }
    } else if (special_property == PROP_REQUIRED) {
        if (index < required) {
            if (PropertyList.Required.pList) {
                property = PropertyList.Required.pList[index];
            }
        }
    } else if (special_property == PROP_OPTIONAL) {
        if (index < optional) {
            if (PropertyList.Optional.pList) {
                property = PropertyList.Optional.pList[index];
            }
        }
    }

    return (BACNET_PROPERTY_ID) property;
}

unsigned property_list_special_count(
    BACNET_OBJECT_TYPE object_type,
    BACNET_PROPERTY_ID special_property)
{
    unsigned count = 0; /* return value */
    struct special_property_list_t PropertyList = { {0} };

    property_list_special(object_type, &PropertyList);
    if (special_property == PROP_ALL) {
        count =
            PropertyList.Required.count + PropertyList.Optional.count +
            PropertyList.Proprietary.count;
    } else if (special_property == PROP_REQUIRED) {
        count = PropertyList.Required.count;
    } else if (special_property == PROP_OPTIONAL) {
        count = PropertyList.Optional.count;
    }

    return count;
}
#endif


// defined above!
///**
// * Function that returns the number of BACnet object properties in a list
// *
// * @param pList - array of type 'int' that is a list of BACnet object
// * properties, terminated by a 'MAX_BACNET_PROPERTY_ID' value.
// */
//// todo 2 - this function appears in 3 places....
//unsigned property_list_count(
//    const BACNET_PROPERTY_ID *pList)
//{
//    unsigned property_count = 0;
//
//    if (pList) {
//        while (*pList != MAX_BACNET_PROPERTY_ID) {
//            property_count++;
//            pList++;
//        }
//    }
//
//    return property_count;
//}

/**
 * ReadProperty handler for this property.  For the given ReadProperty
 * data, the application_data is loaded or the error flags are set.
 *
 * @param  rpdata - ReadProperty data, including requested data and
 * data for the reply, or error response.
 *
 * @return number of APDU bytes in the response, or
 * BACNET_STATUS_ERROR on error.
 */
int property_list_encode(
    BACNET_READ_PROPERTY_DATA *rpdata,
    const BACNET_PROPERTY_ID *pListRequired,
    const BACNET_PROPERTY_ID *pListOptional,
    const BACNET_PROPERTY_ID *pListProprietary)
{
    int apdu_len = 0;   /* return value */
    uint8_t *apdu ;
    int max_apdu_len ;
    uint32_t count ;
    unsigned required_count ;
    unsigned optional_count ;
    unsigned proprietary_count ;
    int len = 0;
    unsigned i = 0; /* loop index */

    required_count = property_list_count(pListRequired);
    optional_count = property_list_count(pListOptional);
    proprietary_count = property_list_count(pListProprietary);
    /* total of all counts */
    count = required_count + optional_count + proprietary_count;
    if (required_count >= 3) {
        /* less the 3 always required properties */
        count -= 3;
    } else {
        count = 0;
    }

    if ((rpdata == NULL) || (rpdata->application_data == NULL) ||
        (rpdata->application_data_len == 0)) {
        return 0;
    }
    apdu = rpdata->application_data;

    max_apdu_len = rpdata->application_data_len;

    switch (rpdata->object_property) {
        case PROP_PROPERTY_LIST:
            if (rpdata->array_index == 0) {
                /* Array element zero is the number of elements in the array */
                apdu_len =
                    encode_application_unsigned(&apdu[0], count);
            } else if (rpdata->array_index == BACNET_ARRAY_ALL) {
                /* if no index was specified, then try to encode the entire list */
                /* into one packet. */
                if (required_count > 3) {
                    for (i = 0; i < required_count; i++) {
                        if ((pListRequired[i] == PROP_OBJECT_TYPE) ||
                            (pListRequired[i] == PROP_OBJECT_IDENTIFIER) ||
                            (pListRequired[i] == PROP_OBJECT_NAME)) {
                            continue;
                        } else {
                            len =
                                encode_application_enumerated(&apdu[apdu_len],
                                (uint32_t)pListRequired[i]);
                        }
                        /* add it if we have room */
                        if ((apdu_len + len) < max_apdu_len) {
                            apdu_len += len;
                        } else {
                            rpdata->error_code =
                                ERROR_CODE_ABORT_SEGMENTATION_NOT_SUPPORTED;
                            apdu_len = BACNET_STATUS_ABORT;
                            break;
                        }
                    }
                }
                if (optional_count) {
                    for (i = 0; i < optional_count; i++) {
                        len =
                            encode_application_enumerated(&apdu[apdu_len],
                            (uint32_t)pListOptional[i]);
                        /* add it if we have room */
                        if ((apdu_len + len) < max_apdu_len) {
                            apdu_len += len;
                        } else {
                            rpdata->error_code =
                                ERROR_CODE_ABORT_SEGMENTATION_NOT_SUPPORTED;
                            apdu_len = BACNET_STATUS_ABORT;
                            break;
                        }
                    }
                }
                if (proprietary_count) {
                    for (i = 0; i < proprietary_count; i++) {
                        len =
                            encode_application_enumerated(&apdu[apdu_len],
                            (uint32_t)pListProprietary[i]);
                        /* add it if we have room */
                        if ((apdu_len + len) < max_apdu_len) {
                            apdu_len += len;
                        } else {
                            rpdata->error_code =
                                ERROR_CODE_ABORT_SEGMENTATION_NOT_SUPPORTED;
                            apdu_len = BACNET_STATUS_ABORT;
                            break;
                        }
                    }
                }
            } else {
                if (rpdata->array_index <= count) {
                    count = 0;
                    if (required_count > 3) {
                        for (i = 0; i < required_count; i++) {
                            if ((pListRequired[i] == PROP_OBJECT_TYPE) ||
                                (pListRequired[i] == PROP_OBJECT_IDENTIFIER) ||
                                (pListRequired[i] == PROP_OBJECT_NAME)) {
                                continue;
                            } else {
                                count++;
                            }
                            if (count == rpdata->array_index) {
                                apdu_len = encode_application_enumerated(
                                    &apdu[apdu_len],
                                    (uint32_t)pListRequired[i]);
                                break;
                            }
                        }
                    }
                    if ((apdu_len == 0) && (optional_count > 0)) {
                        for (i = 0; i < optional_count; i++) {
                            count++;
                            if (count == rpdata->array_index) {
                                apdu_len = encode_application_enumerated(
                                    &apdu[apdu_len],
                                    (uint32_t)pListOptional[i]);
                                break;
                            }
                        }
                    }
                    if ((apdu_len == 0) && (proprietary_count > 0)) {
                        for (i = 0; i < proprietary_count; i++) {
                            count++;
                            if (count == rpdata->array_index) {
                                apdu_len = encode_application_enumerated(
                                    &apdu[apdu_len],
                                    (uint32_t)pListProprietary[i]);
                                break;
                            }
                        }
                    }
                } else {
                    rpdata->error_class = ERROR_CLASS_PROPERTY;
                    rpdata->error_code = ERROR_CODE_INVALID_ARRAY_INDEX;
                    apdu_len = BACNET_STATUS_ERROR;
                }
            }
            break;
        default:
            rpdata->error_class = ERROR_CLASS_PROPERTY;
            rpdata->error_code = ERROR_CODE_UNKNOWN_PROPERTY;
            apdu_len = BACNET_STATUS_ERROR;
            break;
    }

    return apdu_len;
}

#ifdef TEST
#include <assert.h>
#include <string.h>
#include "ctest.h"

void testPropList(
    Test * pTest)
{
    unsigned i = 0, j = 0;
    unsigned count = 0;
    BACNET_PROPERTY_ID property = MAX_BACNET_PROPERTY_ID;
    unsigned object_id = 0, object_name = 0, object_type = 0;

    for (i = 0; i < OBJECT_PROPRIETARY_MIN; i++) {
        count = property_list_special_count((BACNET_OBJECT_TYPE) i, PROP_ALL);
        ct_test(pTest, count >= 3);
        object_id = 0;
        object_name = 0;
        object_type = 0;
        for (j = 0; j < count; j++) {
            property =
                property_list_special_property((BACNET_OBJECT_TYPE) i,
                                               PROP_ALL, j);
            if (property == PROP_OBJECT_TYPE) {
                object_type++;
            }
            if (property == PROP_OBJECT_IDENTIFIER) {
                object_id++;
            }
            if (property == PROP_OBJECT_NAME) {
                object_name++;
            }
        }
        ct_test(pTest, object_type == 1);
        ct_test(pTest, object_id == 1);
        ct_test(pTest, object_name == 1);
    }
}

#ifdef TEST_PROPLIST
int main(
    void)
{
    Test *pTest;
    bool rc;

    pTest = ct_create("BACnet Property List", NULL);
    /* individual tests */
    rc = ct_addTestFunction(pTest, testPropList);
    assert(rc);

    ct_setStream(pTest, stdout);
    ct_run(pTest);
    (void) ct_report(pTest);
    ct_destroy(pTest);

    return 0;
}
#endif /* TEST_PROPLIST */
#endif /* TEST */

